@start_url = http://localhost:3022

###
GET {{start_url}}/

###
GET {{start_url}}/toto

###
POST {{start_url}}/api/object/add
Content-Type: application/json

{
  "name": "object 1",
  "quantity": 2
}

###
GET {{start_url}}/api/object/

###
GET {{start_url}}/api/object/1

###
PUT {{start_url}}/api/object/2
Content-Type: application/json

{
  "name": "object 42",
  "quantity": 69
}

###
DELETE {{start_url}}/api/object/1
