@start_url = http://localhost:3022





###
POST {{start_url}}/api/users/local/register
Content-Type: application/json

{
  "name": "Thomas",
  "email": "thomaslaforge@gmail.com",
  "password": "tomtom1234"
}

###
POST {{start_url}}/api/users/local/register
Content-Type: application/json

{
  "name": "Jérémy",
  "email": "jeremyfelix41@gmail.com",
  "password": "Bloupy73!"
}




###
GET {{start_url}}/

###
GET {{start_url}}/toto

###
POST {{start_url}}/api/objects/
Content-Type: application/json

{
  "name": "object 1",
  "quantity": 2
}

###
GET {{start_url}}/api/objects/

###
GET {{start_url}}/api/objects/1

###
PUT {{start_url}}/api/objects/2
Content-Type: application/json

{
  "name": "object 42",
  "quantity": 65
}

###
DELETE {{start_url}}/api/objects/1
